@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class Main {
    +{static}main(args : String[])
}

package inscryption
{
    class PlateauAffichage {
            - m_datas : GameManager
            - m_player : Player
            - m_opponent : Opponent
            + displayGameBoard() : void
            + displayCards() : void
            + displayRows() : String
            + toString() : String

        }

        class GameManager {
            -m_score : Integer
            -m_turn : Integer
            -m_draw : Boolean

            +<<create>>GameManager(player : Player, opponent : Opponent)
            +manageAction() : Boolean
            +nextTurn() : void
            +placeCard(indHand : Integer, indBoard : Integer) : void
            +gameReview() : Boolean
            +getScore() : Integer
            +setScore(attack : Integer) : void
            +getTurn() : Integer
            +getCards() : Cartes[][]
            +getHand() : ArrayList<Cartes_animaux>
            +getDraw() : ArrayList<Cartes_animaux>
            +getPlayer() : Player
            +getOpponent() : Opponent
            +setGame(match : Integer, opponent : Opponent) : void
            +setCard(carte : Cartes, row : Integer, columns : Integer) : void
            + toString() : String
        }

        enum PowerEnum <<enumeration>> {
            Many_Lives
            Grow
            Stinky
            Runner
            Death_Touch
            Sharp_Spikes
            +toString() : String
        }



        package players {

        class Player {
            -m_random : Random
            -m_obtainedBones : int
            +<<create>>Player()
             +setGameManager(gameManager : GameManager) : void
             +createDraw() : void
             +draw() : void
             +attack() : void
             +removeCard(indHand : Integer) : Cartes
             +getHand() : ArrayList<Cartes_animaux>
             +getDraw() : ArrayList<Cartes_animaux>
             +getPlayerBones() : Integer
             +setPlayerBones(nb : Integer) : void
             +increaseBones() : void
             +toString() : String

        }
        class Opponent {

            +setGameManager(gameManager : GameManager) : void
            + setFirstMatch() : Void
            + setSecondMatch() : Void
            + setThirdMatch() : Void
            + play() : void
            +attack() : void
            +toString() : String

        }


        }



    package cartes {

        abstract class Cartes <<abstract>>{
            -m_name : String
            -m_health_points : Integer
            -m_animals : Cartes_animaux
            +<<create>> Cartes_obstacles(nom : String , pdv : Integer)
            +getName() : String
            +getHealthPoints() : Integer
            +takeDamage() : void
            +setAnimals(animal : Cartes_animaux) : void
            +getAnimals() : Cartes_animaux
            +toString() : String

        }

        abstract class Cartes_animaux<<abstract>> extends Cartes{
        -m_attack : Integer
        -m_blood : Integer
        -m_bones : Integer
        -m_flying : Boolean
        +<<create>>Cartes_animaux(nom : String, att : Integer, pdv : Integer, gds : Integer, os : Integer, vol : Boolean)
        +getAttack() : Integer
        +getBlood(): Integer
        +getBones() : Integer
        +isFlying() : Boolean
        +toString() : String
        }
        class Chat extends Cartes_animaux{
            +<<create>>Chat()
            +toString() : String
        }
        class Grizzly extends Cartes_animaux{
            +<<create>>Grizzly()
            +toString() : String
        }
        class Coyote extends Cartes_animaux{
            +<<create>>Coyote()
            +toString() : String
        }
        class Moineau extends Cartes_animaux{
            +<<create>>Moineau()
            +toString() : String
        }
        class Corbeau extends Cartes_animaux{
            +<<create>>Corbeau()
            +toString() : String
        }
        class Ecureuil extends Cartes_animaux{
            +<<create>>Ecureuil()
            +toString() : String
        }
        class Hermine extends Cartes_animaux{
            +<<create>>Hermine()
            +toString() : String
        }
        class Louveteau extends Cartes_animaux{
            +<<create>>Louveteau()
            +toString() : String
        }
        class Loup extends Cartes_animaux{
            +<<create>>Loup()
            +toString() : String
        }
        class Punaise extends Cartes_animaux{
            +<<create>>Punaise()
            +toString() : String
        }
        class Elan extends Cartes_animaux{
            +<<create>>Elan()
            +toString() : String
        }
        class Porc_epic extends Cartes_animaux{
                    +<<create>>Porc_epic()
                    +toString() : String
        }
        class Vipere extends Cartes_animaux{
                    +<<create>>Vipere()
                    +toString() : String
        }
        class Rocher extends Cartes{
            +<<create>>Rocher()
            +toString() : String
        }
        class Sapin extends Cartes{
            +<<create>>Sapin()
            +toString() : String
        }
    }
}

Cartes_animaux --> "m_power \n 1" PowerEnum
Player *--> "- m_main \n 0..*" Cartes_animaux
Player *--> "- m_gamecards \n 10" Cartes_animaux
Player o--> "-m_datas \n 1" GameManager
Player ..> PowerEnum : <<uses>>
Opponent o--> "- m_actions : Cartes[0..4] \n 4" Cartes
Opponent o--> "-m_datas \n 1" GameManager
Opponent ..> PowerEnum : <<uses>>
GameManager o--> "-m_player \n 1" Player
GameManager o--> "-m_opponent \n 1" Opponent
GameManager o--> "-m_gameboard : Cartes[0..4] \n 3" Cartes
GameManager ..> PowerEnum : <<uses>>
PlateauAffichage o--> "-m_datas \n 1" GameManager
Main .-> PlateauAffichage : <<create>>
Main .-> GameManager : <<create>>
Main .-> Player : <<create>>
Main .-> Opponent : <<create>>
Main .-> inscryption : <<uses>>
@enduml