@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class Main {
    +{static}main(args : String[])
}

package inscryption
{
    class DisplayBoard {
            - m_datas : GameManager
            - m_player : Player
            - m_opponent : Opponent
            + displayGameBoard() 
            + displayCards() 
            + displayRows() : String
            + prInteger(chaine : String) 
            + toString() : String

        }

        class GameManager {
            -m_score : Integereger
            -m_turn : Integereger
            -m_draw : Boolean
            -m_game : Integereger
            -m_message : String

            +<<create>>GameManager(player : Player, opponent : Opponent)
            + manageAction(s : Scanner) 
            + nextTurn() 
            + placeCard(i : Integer, j : Integer) 
            + setMessage(msg : String) 
            + getMessage() : String
            + gameReview() : Boolean
            + getScore() : Integer
            + setScore(score : Integer) 
            + getTurn() : Integer
            + isCard(i : Integer, j : Integer) : Boolean
            + isCardAnimal(i : Integer, j : Integer) : Boolean
            + getHandSize() : Integer
            + getCardName(i : Integer, j : Integer) : String
            + getCardHealthPoIntegers(i : Integer, j : Integer) : Integer
            + getCardAttack(i : Integer, j : Integer) : Integer
            + getCardFly(i : Integer, j : Integer) : Boolean
            + getCardPowerSize(i : Integer, j : Integer) : Integer
            + getCardPowerFirst(i : Integer, j : Integer) : PowerEnum
            + getCardPowerLast(i : Integer, j : Integer) : PowerEnum
            + cardTakeDamage(i : Integer, j : Integer, k : Integer) 
            + getDrawSize() : Integer
            + getCardNameInHand(i : Integer) : String
            + getCardAttackInHand(i : Integer) : Integer
            + getCardHealthPoIntegerInHand(i : Integer) : Integer
            + getCardBloodInHand(i : Integer) : Integer
            + getCardBonesInHand(i : Integer) : Integer
            + getCardFirstPowerInHand(i : Integer) : PowerEnum
            + getCardLastPowerInHand(i : Integer) : PowerEnum
            + getCardFlyInHand(i : Integer) : Boolean
            + moveCardToRow1(i : Integer) 
            + moveCard(i : Integer, j : Integer, k : Integer) 
            + getGame() : Integer
            + getAnimalAttack(i : Integer, j : Integer) : Integer
            + getPlayerBones() : Integer
            + getPlayerTurnAttack() : Integer
            + getOpponentTurnAttack() : Integer
            + setGame(game : Integer) 
            + proposeAddToDraw(s : Scanner) 
            + displaySacrificeStone(s : Scanner) 
            + logicSacrificeStone(i : Integer, s : Scanner) 
            + setCard(c : Cards, i : Integer, j : Integer) 
            + toString() : String
        }

        class Location{
            -m_x : Integer
            -m_y : Integer
            -m_damage : Integer
            -m_damageAction : Boolean
        }

        class AttackResult{
            -m_score : Integer
        }


        enum PowerEnum <<enumeration>> {
            Many_Lives
            Grow
            Stinky
            Runner
            Death_Touch
            Sharp_Spikes
            +toString() : String
        }



        package players {

        class Player {
            -m_obtainedBones : Integer
            +<<create>>Player()
            + setGameManager(gameManager : GameManager) 
            + createDraw() 
            + draw() 
            + setGamecards() 
            + getDrawSize() : Integer
            + getAnimalAtInDraw(i : Integer) : Animals_cards
            + removeAtInDraw(i : Integer) 
            + addInDraw(ca : Animals_cards) 
            + getTurnAttack() : Integer
            + attack(gameboard : Cards[][]) : AttackResult
            + removeCard(i : Integer) : Cards
            + getHandSize() : Integer
            + isDrawEmpty() : boolean
            + getBones() : Integer
            + getBloodAt(i : Integer) : Integer
            + getBonesAt(i : Integer) : Integer
            + setBones(bones : Integer) 
            + increaseBones() 
            + getCardPowerFirst(i : Integer) : PowerEnum
            + getCardNameInHand(i : Integer) : String
            + getCardAttackInHand(i : Integer) : Integer
            + getCardHealthPoIntegerInHand(i : Integer) : Integer
            + getCardBloodInHand(i : Integer) : Integer
            + getCardBonesInHand(i : Integer) : Integer
            + getCardFirstPowerInHand(i : Integer) : PowerEnum
            + getCardLastPowerInHand(i : Integer) : PowerEnum
            + getCardFlyInHand(i : Integer) : Boolean
            + toString() : String

        }
        class Opponent {

            +setGameManager(gameManager : GameManager) 
            + setMatch() 
            + play() 
            + getTurnAttack() : Integer
            + attack() 
            + toString() : String

        }


        }



    package cards {

        abstract class Cards <<abstract>>{
            -m_name : String
            -m_health_poIntegers : Integereger
            -m_animals : Animals_cards
            +<<create>> Cards_obstacles(nom : String , pdv : Integereger)
            +getName() : String
            +getHealthPoIntegers() : Integereger
            +takeDamage() 
            +setAnimals(animal : Animals_cards) 
            +getAnimals() : Animals_cards
            + {abstract} isCardAnimal() : boolean
            + toString() : String

        }

        abstract class Animals_cards<<abstract>> extends Cards{
        -m_attack : Integereger
        -m_blood : Integereger
        -m_bones : Integereger
        -m_flying : Boolean
        +<<create>>Animals_cards(nom : String, att : Integereger, pdv : Integereger, gds : Integereger, os : Integereger, vol : Boolean)
        +getAttack() : Integereger
        +getBlood(): Integereger
        +getBones() : Integereger
        +isFlying() : Boolean
        +isCardAnimal() : Boolean
        }
        class Chat extends Animals_cards{
            +<<create>>Chat()
            +toString() : String
        }
        class Grizzly extends Animals_cards{
            +<<create>>Grizzly()
            +toString() : String
        }
        class Coyote extends Animals_cards{
            +<<create>>Coyote()
            +toString() : String
        }
        class Moineau extends Animals_cards{
            +<<create>>Moineau()
            +toString() : String
        }
        class Corbeau extends Animals_cards{
            +<<create>>Corbeau()
            +toString() : String
        }
        class Ecureuil extends Animals_cards{
            +<<create>>Ecureuil()
            +toString() : String
        }
        class Hermine extends Animals_cards{
            +<<create>>Hermine()
            +toString() : String
        }
        class Louveteau extends Animals_cards{
            +<<create>>Louveteau()
            +toString() : String
        }
        class Loup extends Animals_cards{
            +<<create>>Loup()
            +toString() : String
        }
        class Punaise extends Animals_cards{
            +<<create>>Punaise()
            +toString() : String
        }
        class Elan extends Animals_cards{
            +<<create>>Elan()
            +toString() : String
        }
        class Porc_epic extends Animals_cards{
                    +<<create>>Porc_epic()
                    +toString() : String
        }
        class Vipere extends Animals_cards{
                    +<<create>>Vipere()
                    +toString() : String
        }
        class Rocher extends Cards{
            +<<create>>Rocher()
            +toString() : String
        }
        class Sapin extends Cards{
            +<<create>>Sapin()
            +toString() : String
        }
    }
}

Animals_cards --> "m_power \n 1" PowerEnum
Player o--> "- m_hand \n 0..15*" Animals_cards
Player o--> "- m_gamecards \n 15" Animals_cards
Player o--> "- m_gamecards_copy \n 15" Animals_cards
Player ..> PowerEnum : <<uses>>
Player ..> Location : <<uses>>
Player ..> AttackResult : <<uses>>
Opponent o--> "- m_actions : AnimalCards \n 12" Cards
Opponent ..> PowerEnum : <<uses>>
GameManager *--> "-m_player \n 1" Player
GameManager *--> "-m_opponent \n 1" Opponent
GameManager *--> "-m_gameboard : Cards \n 9" Cards
GameManager ..> PowerEnum : <<uses>>
GameManager o--> "-m_display \n 1" DisplayBoard
Location o--> "-m_card \n 1" Cards
AttackResult o--> "m_locs \n 0..*" Location
Main .-> DisplayBoard : <<create>>
Main .-> GameManager : <<create>>
Main .-> Player : <<create>>
Main .-> Opponent : <<create>>
Main .-> inscryption : <<uses>>
@enduml